services:
  - type: web
    name: taxcalc-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: FLASK_DEBUG
        value: "0"
    plan: free
